import Head from 'next/head'
import Image from 'next/image'
import CakeList from '../components/CakeList'
import { Featured } from '../components/Featured'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cake Shop in Kandy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured/>
      <CakeList/>
    </div>
  )
}
